[tool.poetry]
name = "test-b"
version = "0.1.0"
description = ""
authors = ["Sungan-Kang "]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
chalice = "^1.27.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
